/**
 * Environment bootstrapper for sandboxes/CI where the working tree is wiped
 * between sessions (node_modules, .env, build caches are not persisted).
 *
 *   npx tsx scripts/bootstrap-env.ts
 *
 * Behavior:
 *  - If `.env` exists it is left untouched (never clobbers local config).
 *  - Otherwise writes a minimal sandbox `.env` (embedded PGlite, console
 *    email) with cryptographically generated secrets.
 *  - Generated secrets are persisted OUTSIDE the repo at
 *    $HOME/opt/.payflow-secrets.json so repeated bootstraps reuse the same
 *    AUTH_SECRET/ENCRYPTION_KEY (sessions + encrypted data survive rebuilds).
 *
 * On a normal developer machine you would instead: cp .env.example .env
 */
import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import crypto from "node:crypto";

const SECRETS_STORE = join(homedir(), "opt", ".payflow-secrets.json");
const ENV_PATH = join(process.cwd(), ".env");

interface PersistedSecrets {
  AUTH_SECRET: string;
  ENCRYPTION_KEY: string;
}

function loadOrCreateSecrets(): PersistedSecrets {
  if (existsSync(SECRETS_STORE)) {
    try {
      const parsed = JSON.parse(readFileSync(SECRETS_STORE, "utf8")) as Partial<PersistedSecrets>;
      if (
        typeof parsed.AUTH_SECRET === "string" &&
        parsed.AUTH_SECRET.length >= 32 &&
        typeof parsed.ENCRYPTION_KEY === "string" &&
        /^[0-9a-f]{64}$/i.test(parsed.ENCRYPTION_KEY)
      ) {
        return { AUTH_SECRET: parsed.AUTH_SECRET, ENCRYPTION_KEY: parsed.ENCRYPTION_KEY };
      }
    } catch {
      // fall through and regenerate
    }
  }
  const secrets: PersistedSecrets = {
    AUTH_SECRET: crypto.randomBytes(36).toString("base64url"),
    ENCRYPTION_KEY: crypto.randomBytes(32).toString("hex"),
  };
  mkdirSync(dirname(SECRETS_STORE), { recursive: true });
  writeFileSync(SECRETS_STORE, JSON.stringify(secrets, null, 2));
  chmodSync(SECRETS_STORE, 0o600);
  return secrets;
}

function main(): void {
  if (existsSync(ENV_PATH)) {
    console.log(".env already present — nothing to do.");
    return;
  }
  const secrets = loadOrCreateSecrets();
  const home = homedir();
  const content = [
    "# Auto-generated by scripts/bootstrap-env.ts (offline sandbox profile).",
    "# Recreate on a developer machine with: cp .env.example .env",
    "NODE_ENV=development",
    'DATABASE_URL="postgresql://postgres:postgres@127.0.0.1:5432/postgres?schema=public"',
    "DB_DRIVER=pglite",
    `PGLITE_DATA="${home}/opt/pglite-data"`,
    `AUTH_SECRET="${secrets.AUTH_SECRET}"`,
    `ENCRYPTION_KEY="${secrets.ENCRYPTION_KEY}"`,
    'APP_URL="http://localhost:3000"',
    "EMAIL_PROVIDER=console",
    "BILLING_PROVIDER=mock",
    "",
  ].join("\n");
  writeFileSync(ENV_PATH, content);
  chmodSync(ENV_PATH, 0o600);
  console.log(".env created (PGlite embedded DB, console email, persisted secrets).");
}

main();
